version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn make-it-beautiful

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test

  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - lint
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master