version: 2
jobs:
  lint:
    docker:
      - image: cimg/node:14.18.3
    steps:
      - checkout
      - run: yarn
      - run: yarn make-it-beautiful

  # test:
  #   docker:
  #     - image: cimg/node:14.18.3
  #   steps:
  #     - checkout
  #     - run: yarn
  #     - run: yarn build
  #     - run: yarn test

  release:
    docker:
      - image: cimg/node:14.18.3
    steps:
      - checkout
      - run: node --version
      - run: yarn
      - run: yarn build
      - run: npx semantic-release

workflows:
  version: 2
  lint_and_release:
    jobs:
      - lint
      # - test
      - release:
          requires:
            - lint
          filters:
            branches:
              only: master